### ISSUE TITLE
Samsung Chromebook Plus v2 XE520QAB (WORKS)

### ISSUE THREAD

**Issue by ShapeShifter499** [WeirdTreeThing/chromebook-linux-audio#21]
I recently acquired this computer. I went through the process of installing Mr. Chromebox's firmware and installing Arch Linux.

I stumbled here after some searching online. I have tested that this works fine for my device to enable audio. I was wondering, what might it take to get this added upstream so it is included by default in future Linux Distros?

**Comment by WeirdTreeThing** [comment]
Nautilus uses AVS so things needed are:

1. Selecting the AVS driver by default on Chrome platforms, instead of the legacy SKL driver.
2. AVS firmware and topology needs to be packaged and preinstalled by distros, the firmware is part of linux-firmware so that's already there but topology is separate.
3. I need to merge my AVS UCM into alsa-ucm-conf so that it gets included in the distro's package.

**Comment by WeirdTreeThing** [comment]
Oh and not to mention that when using pipewire, a wireplumber config is needed for the internal mic to function.

**Comment by ShapeShifter499** [comment]
what about getting the speaker support into the sof-firmware project?

**Comment by ShapeShifter499** [comment]
https://github.com/thesofproject/avs-topology-xml

**Comment by WeirdTreeThing** [comment]
The repo you linked is for the AVS driver topology. SOF is not supported on Skylake or Kabylake.

**Comment by ShapeShifter499** [comment]
> The repo you linked is for the AVS driver topology. SOF is not supported on Skylake or Kabylake.

I see, I'm sorry for my confusion
